'''
non agentic ai 
messages : 
System message : system instructions
Human message : user prompt
AI message : output generated by the AI
Tool Message : tool output (agentic ai)

conversation history : 
'''

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from dotenv import load_dotenv
load_dotenv(override=True)
import os

model = ChatOpenAI(model="gpt-4o")

# chat history : all the messages exchanged between the user and the AI
# will be appended here

chat_history = [
    SystemMessage(content="You are a helpful assistant.\
        You answer the user's questions based on the context provided.\
        You dont make up any answers"),
]

while True:
    user_input = input("User: ")
    chat_history.append(HumanMessage(content=user_input))
    if user_input =="exit":
        break
    result = model.invoke(chat_history)
    chat_history.append(AIMessage(content=result.content))
    print("AI: ", result.content)

print("Exiting the chat. Goodbye!")
print("Chat history:", chat_history)